version: '3.8'
  
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: wild2
      MYSQL_DATABASE: wild2
      MYSQL_USER: wild2
      MYSQL_PASSWORD: wild2
    ports:
      - "3306:3306"  # 로컬 포트를 MariaDB에 연결
    volumes:
      - mariadb_data:/var/lib/mysql  # 로컬 볼륨을 MariaDB의 데이터 폴더에 마운트
    networks:
      portainer_default:
        ipv4_address: 172.19.0.11  # 선택 사항: 고정 IP 주소 설정

  nodeapp:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3001:3001"  # 로컬 포트를 Node.js 애플리케이션에 연결
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: wild2
      DB_PASSWORD: wild2
      DB_NAME: wild2
    networks:
      portainer_default:
        ipv4_address: 172.19.0.10  # 선택 사항: 고정 IP 주소 설정

volumes:
  mariadb_data:  # 로컬에 저장할 볼륨을 생성

networks:
  portainer_default:
    external: true

