services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: wild2
      MYSQL_DATABASE: wild2
      MYSQL_USER: wild2
      MYSQL_PASSWORD: wild2
    ports:
      - "3306:3306"  # 로컬 포트를 MariaDB에 연결
    volumes:
      - mariadb_data:/var/lib/mysql  # 로컬 볼륨을 MariaDB의 데이터 폴더에 마운트

  nodeapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"  # 로컬 포트를 Node.js 애플리케이션에 연결
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: wild2
      DB_PASSWORD: wild2
      DB_NAME: wild2

volumes:
  mariadb_data:  # 로컬에 저장할 볼륨을 생성
